use RomaniaInvestmentBank;
INSERT INTO Client(id, lastName, firstName, cnp, email, phoneNumber, Address_No, bankAccount_ID, customerAdvisors_No) values("30s60","Suciu","Laurentiu",1870214106069,"suciu.lau@gmail.com","0706190058",1,1,1)
INSERT INTO Client(id, lastName, firstName, cnp, email, phoneNumber, Address_No, customerAdvisors_No) values("t3ayy","Antonescu","Iancu",1941118327494,"iancu_antonescu10@yahoo.com","0702060769",2, 2)
INSERT INTO Client(id, lastName, firstName, cnp, email, phoneNumber, Address_No, bankAccount_ID, customerAdvisors_No) values("pgzen","Stoica","Vladimir",5000112356574,"stoicavladimir@yahoo.com","0706683324",3,2,1)
INSERT INTO Client(id, lastName, firstName, cnp, email, phoneNumber, Address_No, customerAdvisors_No) values("xkwmp","Gusa","Costache",1950310198829,"costi_gusa5@gmail.com","0702053921",4,1)
INSERT INTO Client(id, lastName, firstName, cnp, email, phoneNumber, Address_No, customerAdvisors_No) values("7zxt5","Selymes","Skender",1880814359051,"selymes.ske@gmail.com","0780088080",5, 3)
INSERT INTO Client(id, lastName, firstName, cnp, email, phoneNumber, Address_No, customerAdvisors_No) values("3jyfj","Milosovici","Carol",1991224188035,"carolmilosovici@yahoo.com","0702080818",6, 2)
INSERT INTO Client(id, lastName, firstName, cnp, email, phoneNumber, Address_No, customerAdvisors_No) values("hpr1g","Tanase","Mihai",1700915136866,"mihai.tanase10@gmail.com","0790528592",7, 4)
INSERT INTO Client(id, lastName, firstName, cnp, email, phoneNumber, Address_No, customerAdvisors_No) values("hnurb","Proca","Daria",2800417016563,"dariaaa_proca7@yahoo.com","0702040669", 8, 5)
INSERT INTO Client(id, lastName, firstName, cnp, email, phoneNumber, Address_No, customerAdvisors_No) values("mzdqm","Bogoescu","Cristina",2750501186493,"bogoescu.cristinutza69@yahoo.com","0711376404",9,3)
INSERT INTO Client(id, lastName, firstName, cnp, email, phoneNumber, Address_No, customerAdvisors_No) values("8bxbo","Cernat","Mihai",1901201517310,"cernat_mihai@yahoo.com","0768911302",10,6)
INSERT INTO Client(id, lastName, firstName, cnp, email, phoneNumber, Address_No, customerAdvisors_No) values("hz3uu","Florea","Ionel",1921013136374,"florea_ionel13@gmail.com","0748815932",11,6)
INSERT INTO Client(id, lastName, firstName, cnp, email, phoneNumber, Address_No, customerAdvisors_No) values("wko35","Duma","Denisa",2950326135681,"duma.denisa95@yahoo.com","0723778431",12,6)

INSERT INTO bankAccount(username, password, Deposit_No) values("abc", 123, 1)
INSERT INTO bankAccount(username, password, Deposit_No) values("def", 987, 2)
INSERT INTO bankAccount(username, password, Deposit_No) values("dua", 548, 3)
INSERT INTO bankAccount(username, password, Deposit_No) values("pqa", 717, 4)
INSERT INTO bankAccount(username, password, Deposit_No) values("zsq", 911, 5)
INSERT INTO bankAccount(username, password, Deposit_No) values("jiu", 289, 6)
INSERT INTO bankAccount(username, password, Deposit_No) values("fea", 912, 7)
INSERT INTO bankAccount(username, password, Deposit_No) values("zpq", 898, 8)
INSERT INTO bankAccount(username, password, Deposit_No) values("frt", 112, 9)
INSERT INTO bankAccount(username, password, Deposit_No) values("vcq", 402, 10)
INSERT INTO bankAccount(username, password, Deposit_No) values("iow", 950, 11)
INSERT INTO bankAccount(username, password, Deposit_No) values("yjr", 473, 12)

INSERT INTO Customer_Advisors(FirstName, LastName, CNP, PositionHeld, PhoneNumber, bankAgency_No,Address_No, CustomerAdvisorsPassword_No) values("Dan","Aurel","4321091239781","Branch Manager","0781267832",1, 13,1)
INSERT INTO Customer_Advisors(FirstName, LastName, CNP, PositionHeld, PhoneNumber, bankAgency_No,Address_No, CustomerAdvisorsPassword_No) values("Mircea","Cuza","2836611239452","Branch Manager","0764134996",2, 14,2)
INSERT INTO Customer_Advisors(FirstName, LastName, CNP, PositionHeld, PhoneNumber, bankAgency_No,Address_No, CustomerAdvisorsPassword_No) values("Vasile","Dumitru","1851104357061","Branch Manager","0744628391",3, 15,3)
INSERT INTO Customer_Advisors(FirstName, LastName, CNP, PositionHeld, PhoneNumber, bankAgency_No,Address_No, CustomerAdvisorsPassword_No) values("Rodica","Maria","2851104328100","Branch Manager","0736116573",4, 16,4)
INSERT INTO Customer_Advisors(FirstName, LastName, CNP, PositionHeld, PhoneNumber, bankAgency_No,Address_No, CustomerAdvisorsPassword_No) values("Andreea","Simionescu","2900818329109","Branch Manager","0765229172",5, 17,5)
INSERT INTO Customer_Advisors(FirstName, LastName, CNP, PositionHeld, PhoneNumber, bankAgency_No,Address_No, CustomerAdvisorsPassword_No) values("Raluca","Zaharie","4826980145271","Branch Manager","0768735612",6, 18,6)

INSERT INTO bankAgency(id, phoneBankNumber, operatingMorningHours, operatingAfternoonHours, lunchBreak,Address_No) values("fk39z", "0256302014", "09:15-13:00", "13:30-17:00", "13:00-13:30", 19)
INSERT INTO bankAgency(id, phoneBankNumber, operatingMorningHours, operatingAfternoonHours, lunchBreak,Address_No) values("pz6g1", "0374477294", "09:15-13:00", "13:30-17:00", "13:00-13:30", 20)
INSERT INTO bankAgency(id, phoneBankNumber, operatingMorningHours, operatingAfternoonHours, lunchBreak,Address_No) values("daq13", "0256244582", "09:15-13:00", "13:30-16:45", "13:00-13:30", 21)
INSERT INTO bankAgency(id, phoneBankNumber, operatingMorningHours, operatingAfternoonHours, lunchBreak,Address_No) values("9h3ad", "0269202530", "08:30-12:30", "13:00-16:15", "12:30-13:00", 22)
INSERT INTO bankAgency(id, phoneBankNumber, operatingMorningHours, operatingAfternoonHours, lunchBreak,Address_No) values("yz89a", "0269252033", "09:30-12:30", "13:00-17:15", "12:30-13:00", 23)
INSERT INTO bankAgency(id, phoneBankNumber, operatingMorningHours, operatingAfternoonHours, lunchBreak,Address_No) values("h7a0q", "0278651644", "09:30-12:30", "13:00-17:15", "12:30-13:00", 24)

INSERT INTO bankAgency(id, phoneBankNumber, operatingMorningHours, operatingAfternoonHours, lunchBreak,Address_No) values("nbsp1", "0269227013", "09:30-12:30", "13:00-17:15", "12:30-13:00", 25)
INSERT INTO bankAgency(id, phoneBankNumber, operatingMorningHours, operatingAfternoonHours, lunchBreak,Address_No) values("l1e39", "0241558826", "08:00-13:00", "13:30-15:45", "13:00-13:30", 26)
INSERT INTO bankAgency(id, phoneBankNumber, operatingMorningHours, operatingAfternoonHours, lunchBreak,Address_No) values("gml8x", "0241510838", "09:00-13:00", "13:30-16:45", "13:00-13:30", 27)
INSERT INTO bankAgency(id, phoneBankNumber, operatingMorningHours, operatingAfternoonHours, lunchBreak,Address_No) values("n918w", "0213140654", "09:15-13:00", "13:30-17:00", "13:00-13:30", 28)
INSERT INTO bankAgency(id, phoneBankNumber, operatingMorningHours, operatingAfternoonHours, lunchBreak,Address_No) values("tuyhx", "0374400327", "09:15-13:00", "13:30-17:00", "13:00-13:30", 29)
INSERT INTO bankAgency(id, phoneBankNumber, operatingMorningHours, operatingAfternoonHours, lunchBreak,Address_No) values("r9caf", "0374289150", "09:15-13:00", "13:30-16:45", "13:00-13:30", 30)

--Adrese clienti
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber, Apartment, Street) values ("Buzau","Buzau","12",null,null,"Bulevardul Industriei")
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber, Apartment, Street) values ("Sibiu","Sibiu",null,"C1", "17","Doljului")
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber, Apartment, Street) values ("Timisoara","Timis","56",null,null,"Libertatii")
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber, Apartment, Street) values ("Miercurea-Ciuc","Harghita","31D",null,null,"Iancu de Hunedoara")
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber, Apartment, Street) values ("Lugoj","Timis","159",null,null,"Closca")
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber, Apartment, Street) values ("Targu-Jiu","Gorj","65A",null,null,"Republicii")
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber, Apartment, Street) values ("Constanta","Constanta","11",null,null,"Bulevardul Ferdinand")
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber, Apartment, Street) values ( "Alba Iulia","Alba","328",null,null,"Nicolae Balcescu")
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber, Apartment, Street) values ("Targu-Jiu","Gorj","86",null,null,"Prahovei")
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber, Apartment, Street) values ("Calarasi","Calarasi","417",null,null,"Rahova")
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber, Apartment, Street) values ("Ovidiu","Constanta",null,"B5","7","Nucilor")
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber, Apartment, Street) values ("Cobadin","Constanta",null,"P3","10","Teilor")

--Adrese consilieri clienti
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber,Apartment, Street) values("Timisoara","Timis","32",null,null,"Florilor")
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber,Apartment, Street) values("Timisoara","Timis",null,"8A",10,"Calea Circumvalatiunii")
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber,Apartment, Street) values("Timisoara","Timis",null,"3C",14,"Calea Sagului")
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber,Apartment, Street) values("Sibiu","Sibiu","54",null,null,"Morii")
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber,Apartment, Street) values("Sibiu","Sibiu","89",null,null,"Calea Austriei")
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber,Apartment, Street) values("Constanta","Constanta",null,"C1",14,"Liliacului")

--Adrese agentii bancare
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber,Apartment, Street) values("Timisoara","Timis","1",null,null,"Socrate")
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber,Apartment, Street) values("Timisoara","Timis","71",null,null,"16 Decembrie 1989")
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber,Apartment, Street) values("Timisoara","Timis","8",null,null,"Zborului")
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber,Apartment, Street) values("Sibiu","Sibiu","39",null,null,"Nicolae Balcescu")
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber,Apartment, Street) values("Sibiu","Sibiu",null,"137",2,"Calea Dumbravei")
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber,Apartment, Street) values("Constanta","Constanta","94",null,null,"Bulevardul Aurel Vlaicu")
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber,Apartment, Street) values("Sibiu","Sibiu",null,"15",2,"Bihorului")
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber,Apartment, Street) values("Constanta","Constanta","34",null,null,"Timisoara")
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber,Apartment, Street) values("Constanta","Constanta",null,"F1",1,"Bulevardul 1 Decembrie 1918")
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber,Apartment, Street) values("Bucuresti",null,"44",null,null,"Bulevardul I. C. Bratianu")
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber,Apartment, Street) values("Bucuresti",null,null,"E1","2","Vintila Voda")
INSERT INTO Address (City, County, HouseNumber, BlockOfFlatsNumber,Apartment, Street) values("Bucuresti",null,null,"P","35","Bulevardul Magheru")

--Depozite clienti
INSERT INTO Deposit (Deposit_RON, Deposit_EUR, Deposit_USD, Deposit_GBP) values (12000, 5000,100, 0)
INSERT INTO Deposit (Deposit_RON, Deposit_EUR, Deposit_USD, Deposit_GBP) values (78859, 0,10000, 30000)
INSERT INTO Deposit (Deposit_RON, Deposit_EUR, Deposit_USD, Deposit_GBP) values (19986, 1830,28374, 11299)
INSERT INTO Deposit (Deposit_RON, Deposit_EUR, Deposit_USD, Deposit_GBP) values (27795, 5925,62025, 34004)
INSERT INTO Deposit (Deposit_RON, Deposit_EUR, Deposit_USD, Deposit_GBP) values (0, 7656,0, 12589)
INSERT INTO Deposit (Deposit_RON, Deposit_EUR, Deposit_USD, Deposit_GBP) values (38928, 2774,27105, 30516)
INSERT INTO Deposit (Deposit_RON, Deposit_EUR, Deposit_USD, Deposit_GBP) values (44547, 9490,51211, 14794)
INSERT INTO Deposit (Deposit_RON, Deposit_EUR, Deposit_USD, Deposit_GBP) values (53284, 9607,38080, 31113)
INSERT INTO Deposit (Deposit_RON, Deposit_EUR, Deposit_USD, Deposit_GBP) values (6421, 8294,35983, 19326)
INSERT INTO Deposit (Deposit_RON, Deposit_EUR, Deposit_USD, Deposit_GBP) values (99972, 12324,49494, 13591)
INSERT INTO Deposit (Deposit_RON, Deposit_EUR, Deposit_USD, Deposit_GBP) values (3293, 0,41511, 25415)
INSERT INTO Deposit (Deposit_RON, Deposit_EUR, Deposit_USD, Deposit_GBP) values (4464, 0,25314, 29091)

--Parole angajati banca
INSERT INTO CustomerAdvisorsPassword(password) values (1234)
INSERT INTO CustomerAdvisorsPassword(password) values (7777)
INSERT INTO CustomerAdvisorsPassword(password) values (9876)
INSERT INTO CustomerAdvisorsPassword(password) values (1212)
INSERT INTO CustomerAdvisorsPassword(password) values (1515)
INSERT INTO CustomerAdvisorsPassword(password) values (5555)
