// Generated by delombok at Wed Jul 19 10:10:00 IDT 2023
package rib.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import org.hibernate.Hibernate;

@Entity
@Table(name = "Address")
public class Address {
	@Id
	@Column(name = "No")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int no;
	@Column(name = "City")
	private String city;
	@Column(name = "County")
	private String county;
	@Column(name = "HouseNumber")
	private String houseNumber;
	@Column(name = "BlockOfFlatsNumber")
	private String blockOfFlatsNumber;
	@Column(name = "Apartment")
	private String apartment;
	@Column(name = "Street")
	private String street;
	@OneToOne(mappedBy = "address")
	private Client client;
	@OneToOne(mappedBy = "address")
	private CustomerAdvisors customerAdvisors;
	@OneToOne(mappedBy = "address")
	private BankAgency bankAgency;

	public Address(int no, String county, String city, String street, String houseNumber, String blockOfFlatsNumber, String apartment) {
		super();
		this.no = no;
		this.county = county;
		this.city = city;
		this.street = street;
		this.houseNumber = houseNumber;
		this.apartment = apartment;
		this.blockOfFlatsNumber = blockOfFlatsNumber;
	}

	@Override
	public String toString() {
		String finalString = "\nAdresa " + this.no + ": ";
		if (Hibernate.isInitialized(this.county) && this.county != null) finalString += "Judet " + this.county + ", ";
		if (Hibernate.isInitialized(this.city) && this.city != null) finalString += "Oras " + this.city + ", ";
		if (Hibernate.isInitialized(this.street) && this.street != null) finalString += "Str. " + this.street + ", ";
		if (Hibernate.isInitialized(this.houseNumber) && this.houseNumber != null) finalString += "Nr. " + this.houseNumber;
		if (Hibernate.isInitialized(this.blockOfFlatsNumber) && this.blockOfFlatsNumber != null) finalString += "Nr. bloc. " + this.blockOfFlatsNumber + ", ";
		if (Hibernate.isInitialized(this.apartment) && this.apartment != null) finalString += "Ap. " + this.apartment;
		// else
		//finalString += "\n";
		return finalString;
	}

	@java.lang.SuppressWarnings("all")
	public int getNo() {
		return this.no;
	}

	@java.lang.SuppressWarnings("all")
	public String getCity() {
		return this.city;
	}

	@java.lang.SuppressWarnings("all")
	public String getCounty() {
		return this.county;
	}

	@java.lang.SuppressWarnings("all")
	public String getHouseNumber() {
		return this.houseNumber;
	}

	@java.lang.SuppressWarnings("all")
	public String getBlockOfFlatsNumber() {
		return this.blockOfFlatsNumber;
	}

	@java.lang.SuppressWarnings("all")
	public String getApartment() {
		return this.apartment;
	}

	@java.lang.SuppressWarnings("all")
	public String getStreet() {
		return this.street;
	}

	@java.lang.SuppressWarnings("all")
	public Client getClient() {
		return this.client;
	}

	@java.lang.SuppressWarnings("all")
	public CustomerAdvisors getCustomerAdvisors() {
		return this.customerAdvisors;
	}

	@java.lang.SuppressWarnings("all")
	public BankAgency getBankAgency() {
		return this.bankAgency;
	}

	@java.lang.SuppressWarnings("all")
	public void setNo(final int no) {
		this.no = no;
	}

	@java.lang.SuppressWarnings("all")
	public void setCity(final String city) {
		this.city = city;
	}

	@java.lang.SuppressWarnings("all")
	public void setCounty(final String county) {
		this.county = county;
	}

	@java.lang.SuppressWarnings("all")
	public void setHouseNumber(final String houseNumber) {
		this.houseNumber = houseNumber;
	}

	@java.lang.SuppressWarnings("all")
	public void setBlockOfFlatsNumber(final String blockOfFlatsNumber) {
		this.blockOfFlatsNumber = blockOfFlatsNumber;
	}

	@java.lang.SuppressWarnings("all")
	public void setApartment(final String apartment) {
		this.apartment = apartment;
	}

	@java.lang.SuppressWarnings("all")
	public void setStreet(final String street) {
		this.street = street;
	}

	@java.lang.SuppressWarnings("all")
	public void setClient(final Client client) {
		this.client = client;
	}

	@java.lang.SuppressWarnings("all")
	public void setCustomerAdvisors(final CustomerAdvisors customerAdvisors) {
		this.customerAdvisors = customerAdvisors;
	}

	@java.lang.SuppressWarnings("all")
	public void setBankAgency(final BankAgency bankAgency) {
		this.bankAgency = bankAgency;
	}

	@java.lang.SuppressWarnings("all")
	public Address() {
	}
}
