// Generated by delombok at Wed Jul 19 10:10:00 IDT 2023
package rib.entity;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import org.hibernate.Hibernate;

@Entity
@Table(name = "Client")
public class Client {
	@Id
	@Column(name = "No")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int no;
	@Column(name = "ID")
	private String id;
	@Column(name = "FirstName")
	private String firstName;
	@Column(name = "LastName")
	private String lastName;
	@Column(name = "CNP")
	private long cnp;
	@Column(name = "Email")
	private String email;
	@Column(name = "PhoneNumber")
	private String phoneNumber;
	@OneToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
	private BankAccount bankAccount;
//	@OneToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
//	@JoinColumn(name = "Deposit_No")
//	private Deposit deposit;
	@OneToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
	@JoinColumn(name = "Address_No")
	private Address address;
	@ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
	private CustomerAdvisors customerAdvisors;

	public Client(String id, String firstName, String lastName, long cnp, String email, Address address, String phoneNumber, CustomerAdvisors customerAdvisors, BankAccount bankAccount) {
		super();
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.cnp = cnp;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.bankAccount = bankAccount;
		this.address = address;
		this.customerAdvisors = customerAdvisors;
	}

	@Override
	public String toString() {
//		String finalString = "\nNr. client " + no + "\nId: " + id + "\nPrenume: " + firstName + "\nNume: "
//				+ lastName + "\nCNP: " + cnp + "\nEmail: " + email + "\nTelefon: " + phoneNumber + "\n";
		String finalString = null;
		if (Hibernate.isInitialized(this.no)) finalString = "\nClient no. " + this.no;
		if (Hibernate.isInitialized(this.id)) finalString += "\nId: " + this.id;
		if (Hibernate.isInitialized(this.firstName)) finalString += "\nFirst name: " + this.firstName;
		if (Hibernate.isInitialized(this.lastName)) finalString += "\nLast name: " + this.lastName;
		if (Hibernate.isInitialized(this.cnp) && this.cnp != 0) finalString += "\nCNP: " + this.cnp;
		if (Hibernate.isInitialized(this.email) && this.email != null) finalString += "\nEmail: " + this.email;
		if (Hibernate.isInitialized(this.phoneNumber) && this.phoneNumber != null) finalString += "\nPhone: " + this.phoneNumber;
		if (Hibernate.isInitialized(this.address) && this.address != null) finalString += "\nAdresa clientului: " + this.address;
		if (Hibernate.isInitialized(this.customerAdvisors) && this.customerAdvisors != null) finalString += this.customerAdvisors;
		return finalString;
	}

	@java.lang.SuppressWarnings("all")
	public int getNo() {
		return this.no;
	}

	@java.lang.SuppressWarnings("all")
	public String getId() {
		return this.id;
	}

	@java.lang.SuppressWarnings("all")
	public String getFirstName() {
		return this.firstName;
	}

	@java.lang.SuppressWarnings("all")
	public String getLastName() {
		return this.lastName;
	}

	@java.lang.SuppressWarnings("all")
	public long getCnp() {
		return this.cnp;
	}

	@java.lang.SuppressWarnings("all")
	public String getEmail() {
		return this.email;
	}

	@java.lang.SuppressWarnings("all")
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	@java.lang.SuppressWarnings("all")
	public BankAccount getBankAccount() {
		return this.bankAccount;
	}

	@java.lang.SuppressWarnings("all")
	public Address getAddress() {
		return this.address;
	}

	@java.lang.SuppressWarnings("all")
	public CustomerAdvisors getCustomerAdvisors() {
		return this.customerAdvisors;
	}

	@java.lang.SuppressWarnings("all")
	public void setNo(final int no) {
		this.no = no;
	}

	@java.lang.SuppressWarnings("all")
	public void setId(final String id) {
		this.id = id;
	}

	@java.lang.SuppressWarnings("all")
	public void setFirstName(final String firstName) {
		this.firstName = firstName;
	}

	@java.lang.SuppressWarnings("all")
	public void setLastName(final String lastName) {
		this.lastName = lastName;
	}

	@java.lang.SuppressWarnings("all")
	public void setCnp(final long cnp) {
		this.cnp = cnp;
	}

	@java.lang.SuppressWarnings("all")
	public void setEmail(final String email) {
		this.email = email;
	}

	@java.lang.SuppressWarnings("all")
	public void setPhoneNumber(final String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@java.lang.SuppressWarnings("all")
	public void setBankAccount(final BankAccount bankAccount) {
		this.bankAccount = bankAccount;
	}

	@java.lang.SuppressWarnings("all")
	public void setAddress(final Address address) {
		this.address = address;
	}

	@java.lang.SuppressWarnings("all")
	public void setCustomerAdvisors(final CustomerAdvisors customerAdvisors) {
		this.customerAdvisors = customerAdvisors;
	}

	@java.lang.SuppressWarnings("all")
	public Client() {
	}
}
