// Generated by delombok at Wed Jul 19 10:10:00 IDT 2023
package rib.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

@Entity
@Table(name = "CustomerAdvisorsPassword")
public class CustomerAdvisorsPassword {
	@Id
	@Column(name = "No")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int no;
	@Column(name = "Password")
	private int password;
	@OneToOne(mappedBy = "customerAdvisorsPassword")
	private CustomerAdvisors customerAdvisors;

	public CustomerAdvisorsPassword(int no, int password, CustomerAdvisors customerAdvisors) {
		super();
		this.no = no;
		this.password = password;
		this.customerAdvisors = customerAdvisors;
	}

	@java.lang.SuppressWarnings("all")
	public int getNo() {
		return this.no;
	}

	@java.lang.SuppressWarnings("all")
	public int getPassword() {
		return this.password;
	}

	@java.lang.SuppressWarnings("all")
	public CustomerAdvisors getCustomerAdvisors() {
		return this.customerAdvisors;
	}

	@java.lang.SuppressWarnings("all")
	public void setNo(final int no) {
		this.no = no;
	}

	@java.lang.SuppressWarnings("all")
	public void setPassword(final int password) {
		this.password = password;
	}

	@java.lang.SuppressWarnings("all")
	public void setCustomerAdvisors(final CustomerAdvisors customerAdvisors) {
		this.customerAdvisors = customerAdvisors;
	}

	@java.lang.SuppressWarnings("all")
	public CustomerAdvisorsPassword() {
	}
}
