// Generated by delombok at Wed Jul 19 10:10:00 IDT 2023
package rib.entity;

import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import org.hibernate.Hibernate;

@Entity
@Table(name = "Customer_Advisors")
public class CustomerAdvisors {
	@Id
	@Column(name = "No")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;
	@Column(name = "FirstName")
	private String firstName;
	@Column(name = "LastName")
	private String lastName;
	@Column(name = "CNP")
	private String cnp;
	@Column(name = "PositionHeld")
	private String positionHeld;
	@Column(name = "PhoneNumber")
	private String phoneNumber;
	@OneToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, mappedBy = "customerAdvisors")
	private List<Client> client;
	@ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
	private BankAgency bankAgency;
	@OneToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
	private Address address;
	@OneToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
	@JoinColumn(name = "CustomerAdvisorsPassword_No")
	private CustomerAdvisorsPassword customerAdvisorsPassword;

	public CustomerAdvisors(String firstName, String lastName, String cnp, String positionHeld, Address address, String phoneNumber, BankAgency bankAgency, CustomerAdvisorsPassword customerAdvisorsPassword) {
		super();
		this.firstName = firstName;
		this.lastName = lastName;
		this.cnp = cnp;
		this.positionHeld = positionHeld;
		this.phoneNumber = phoneNumber;
		this.bankAgency = bankAgency;
		this.address = address;
		this.customerAdvisorsPassword = customerAdvisorsPassword;
	}

	@Override
	public String toString() {
		String finalString;
		finalString = "\nBancher " + id + "\nFunctie: " + positionHeld + "\nNume: " + firstName + " " + lastName + "\nCNP: " + cnp + "\nTelefon: " + phoneNumber;
		if (Hibernate.isInitialized(this.address) && this.address != null) finalString += "\nAdresa bancher: " + this.address;
		if (Hibernate.isInitialized(this.bankAgency) && this.bankAgency != null) finalString += "\nAdresa agentie bancara: " + this.bankAgency.getAddress();
		finalString += "\n";
		return finalString;
	}

	@java.lang.SuppressWarnings("all")
	public int getId() {
		return this.id;
	}

	@java.lang.SuppressWarnings("all")
	public String getFirstName() {
		return this.firstName;
	}

	@java.lang.SuppressWarnings("all")
	public String getLastName() {
		return this.lastName;
	}

	@java.lang.SuppressWarnings("all")
	public String getCnp() {
		return this.cnp;
	}

	@java.lang.SuppressWarnings("all")
	public String getPositionHeld() {
		return this.positionHeld;
	}

	@java.lang.SuppressWarnings("all")
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	@java.lang.SuppressWarnings("all")
	public List<Client> getClient() {
		return this.client;
	}

	@java.lang.SuppressWarnings("all")
	public BankAgency getBankAgency() {
		return this.bankAgency;
	}

	@java.lang.SuppressWarnings("all")
	public Address getAddress() {
		return this.address;
	}

	@java.lang.SuppressWarnings("all")
	public CustomerAdvisorsPassword getCustomerAdvisorsPassword() {
		return this.customerAdvisorsPassword;
	}

	@java.lang.SuppressWarnings("all")
	public void setId(final int id) {
		this.id = id;
	}

	@java.lang.SuppressWarnings("all")
	public void setFirstName(final String firstName) {
		this.firstName = firstName;
	}

	@java.lang.SuppressWarnings("all")
	public void setLastName(final String lastName) {
		this.lastName = lastName;
	}

	@java.lang.SuppressWarnings("all")
	public void setCnp(final String cnp) {
		this.cnp = cnp;
	}

	@java.lang.SuppressWarnings("all")
	public void setPositionHeld(final String positionHeld) {
		this.positionHeld = positionHeld;
	}

	@java.lang.SuppressWarnings("all")
	public void setPhoneNumber(final String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@java.lang.SuppressWarnings("all")
	public void setClient(final List<Client> client) {
		this.client = client;
	}

	@java.lang.SuppressWarnings("all")
	public void setBankAgency(final BankAgency bankAgency) {
		this.bankAgency = bankAgency;
	}

	@java.lang.SuppressWarnings("all")
	public void setAddress(final Address address) {
		this.address = address;
	}

	@java.lang.SuppressWarnings("all")
	public void setCustomerAdvisorsPassword(final CustomerAdvisorsPassword customerAdvisorsPassword) {
		this.customerAdvisorsPassword = customerAdvisorsPassword;
	}

	@java.lang.SuppressWarnings("all")
	public CustomerAdvisors() {
	}
}
