// Generated by delombok at Wed Jul 19 10:10:00 IDT 2023
package rib.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.validation.constraints.Min;
import javax.validation.constraints.Positive;
import org.hibernate.Hibernate;

@Entity
@Table(name = "Deposit")
@Positive
public class Deposit {
	@Id
	@Column(name = "No")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int no;
	@Column(name = "Deposit_RON")
	@Min(0)
	private Integer ron;
	@Column(name = "Deposit_EUR")
	@Min(0)
	private Integer eur;
	@Column(name = "Deposit_USD")
	@Min(0)
	private Integer usd;
	@Column(name = "Deposit_GBP")
	@Min(0)
	private Integer gbp;
	@OneToOne(mappedBy = "deposit")
	private BankAccount bankAccount;

	public Deposit(int no, int ron, int eur, int usd, int gbp, BankAccount bankAccount) {
		super();
		this.no = no;
		this.ron = ron;
		this.eur = eur;
		this.usd = usd;
		this.gbp = gbp;
		this.bankAccount = bankAccount;
	}

	@Override
	public String toString() {
		String finalString = "";
		if (Hibernate.isInitialized(this.no)) finalString += "\nSOLD " + this.no + ": ";
		if (Hibernate.isInitialized(this.ron) && this.getRon() != 0) finalString += "RON: " + this.ron + ", ";
		 else finalString += "";
		if (Hibernate.isInitialized(this.eur) && this.getEur() != 0) finalString += "EUR: " + this.eur + ", ";
		 else finalString += "";
		if (Hibernate.isInitialized(this.usd) && this.getUsd() != 0 && Hibernate.isInitialized(this.gbp) && this.getGbp() != 0) finalString += "USD: " + this.usd + ", ";
		 else if (Hibernate.isInitialized(this.usd) && this.getUsd() != 0 && Hibernate.isInitialized(this.gbp) && this.getGbp() == 0) finalString += "USD: " + this.usd;
		 else finalString += "";
		if (Hibernate.isInitialized(this.gbp) && this.getGbp() != 0) finalString += "GBP: " + this.gbp;
		finalString += "";
		return finalString;
	}

	@java.lang.SuppressWarnings("all")
	public int getNo() {
		return this.no;
	}

	@java.lang.SuppressWarnings("all")
	public Integer getRon() {
		return this.ron;
	}

	@java.lang.SuppressWarnings("all")
	public Integer getEur() {
		return this.eur;
	}

	@java.lang.SuppressWarnings("all")
	public Integer getUsd() {
		return this.usd;
	}

	@java.lang.SuppressWarnings("all")
	public Integer getGbp() {
		return this.gbp;
	}

	@java.lang.SuppressWarnings("all")
	public BankAccount getBankAccount() {
		return this.bankAccount;
	}

	@java.lang.SuppressWarnings("all")
	public void setNo(final int no) {
		this.no = no;
	}

	@java.lang.SuppressWarnings("all")
	public void setRon(final Integer ron) {
		this.ron = ron;
	}

	@java.lang.SuppressWarnings("all")
	public void setEur(final Integer eur) {
		this.eur = eur;
	}

	@java.lang.SuppressWarnings("all")
	public void setUsd(final Integer usd) {
		this.usd = usd;
	}

	@java.lang.SuppressWarnings("all")
	public void setGbp(final Integer gbp) {
		this.gbp = gbp;
	}

	@java.lang.SuppressWarnings("all")
	public void setBankAccount(final BankAccount bankAccount) {
		this.bankAccount = bankAccount;
	}

	@java.lang.SuppressWarnings("all")
	public Deposit() {
	}
}
